### ISSUE TITLE
deferred results broken on compute-separation

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1150]
Um, how did we miss this for so long?

```
plot(1:10)

Error: Invalid typed array length,
From previous event:
at Object.RCloud.promisify_paths.v [as authenticated_cell_evalAsync] (http://127.0.0.1:8080/js/rcloud_bundle.js:129:31)
at rcloud.authenticated_cell_eval (http://127.0.0.1:8080/js/rcloud_bundle.js:535:33)
at Object.result.execute_cell_version (http://127.0.0.1:8080/js/rcloud_bundle.js:2825:20)
at http://127.0.0.1:8080/js/rcloud_bundle.js:2017:63
at start_queue (http://127.0.0.1:8080/js/rcloud_bundle.js:4678:20)
at Object.RCloud.UI.run_button.enqueue (http://127.0.0.1:8080/js/rcloud_bundle.js:4711:17)
at Object.result.enqueue_execution_snapshot (http://127.0.0.1:8080/js/rcloud_bundle.js:2014:34)
at http://127.0.0.1:8080/js/rcloud_bundle.js:1539:35
From previous event:

```

**Comment by gordonwoodhull** [comment]
Although I was confused about the difference between deferred results and inline charts in knitr output, these appear to be the same bug, which is #1133.
