### ISSUE TITLE
warnings not being printed

### ISSUE THREAD

**Issue by rhknag** [att/rcloud#1253]
For 
http://rcloud-5.research.att.com/edit.html?notebook=4c00426807c1ca8f90b2

I get: 

Error: authenticated_cell_eval: Error in eval(expr, envir, enclos) : could not find function "init.context"
at success (http://rcloud-5.research.att.com/js/rcloud_bundle.js:123:23)
From previous event:
at Object.authenticated_cell_evalAsync (http://rcloud-5.research.att.com/js/rcloud_bundle.js:129:31)
at Object.rcloud.authenticated_cell_eval (http://rcloud-5.research.att.com/js/rcloud_bundle.js:528:33)
at Object.result.execute (http://rcloud-5.research.att.com/js/rcloud_bundle.js:2158:34)
at http://rcloud-5.research.att.com/js/rcloud_bundle.js:3120:50
From previous event:
at http://rcloud-5.research.att.com/js/rcloud_bundle.js:3117:32
at Array.map (native)
at Function._.map._.collect (http://rcloud-5.research.att.com/lib/js/underscore.js:98:56)

**Comment by gordonwoodhull** [comment]
What is going on here is that the package is not installed, but the warning message is not being printed.  When I try `require(rzmq)` on the R command line on the same machine, I get

```
Loading required package: rzmq
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘rzmq’
```

Retitling.

**Comment by gordonwoodhull** [comment]
I'm a bit surprised that requiring an uninstalled package is not an error.

**Comment by s-u** [comment]
In general warning are not printed; also try `options(warn=2)` has an odd efect
