### ISSUE TITLE
Error on fresh install on Vagrant box

### ISSUE THREAD

**Issue by dougmet** [att/rcloud#1497]
I've been trying with some success to install RCloud locally on an Ubuntu 14.04 virtual machine running on Virtual Box and setup using Vagrant. The exact vagrant file and provisioning script are in this repo

https://github.com/dougmet/vagrantRcloud

The file bootstrap.sh shows the exact steps I take setting up the machine for RCloud. This file is run as root as soon as the fresh machine comes up.

With version 1.4, RCloud loads but, on a fresh installation with no notebooks, I get the following error in the session window:

```
Error: rcloud.create.notebook: Invalid request.
["Notebook 1"] is not a string.
["# keep snippets here while working with your notebook's cells"] is not a string.
No subschema in "anyOf" matched.
at success (http://192.168.33.10:8080/js/rcloud_bundle.js:182:23)
From previous event:
at rcloud_github_handler (http://192.168.33.10:8080/js/rcloud_bundle.js:185:24)
at Object.rcloud.create_notebook (http://192.168.33.10:8080/js/rcloud_bundle.js:544:20)
at Object.result.create_notebook (http://192.168.33.10:8080/js/rcloud_bundle.js:3456:27)
at http://192.168.33.10:8080/shell_tab.js:115:49
From previous event:
at http://192.168.33.10:8080/shell_tab.js:112:47
From previous event:
at Object.RCloud.UI.with_progress (http://192.168.33.10:8080/js/rcloud_bundle.js:7140:10)
at Object.result.new_notebook (http://192.168.33.10:8080/shell_tab.js:111:30)
From previous event:
at Object.result.new_notebook (http://192.168.33.10:8080/editor_tab.js:1158:18)
at http://192.168.33.10:8080/editor_tab.js:1070:33
From previous event:
at Object.result.init (http://192.168.33.10:8080/editor_tab.js:1049:45)
From previous event:
at http://192.168.33.10:8080/edit.js:37:14
From previous event:
at main (http://192.168.33.10:8080/edit.js:9:27)
at http://192.168.33.10:8080/lib/js/require-common.js:61:17
at Object.context.execCb (http://192.168.33.10:8080/lib/js/require.js:1650:33)
at Object.Module.check (http://192.168.33.10:8080/lib/js/require.js:866:51)
at Object.<anonymous> (http://192.168.33.10:8080/lib/js/require.js:1113:34)
at http://192.168.33.10:8080/lib/js/require.js:132:23
at http://192.168.33.10:8080/lib/js/require.js:1156:21
at each (http://192.168.33.10:8080/lib/js/require.js:57:31)
at Object.Module.emit (http://192.168.33.10:8080/lib/js/require.js:1155:17)
at Object.Module.check (http://192.168.33.10:8080/lib/js/require.js:917:30)
at Object.Module.enable (http://192.168.33.10:8080/lib/js/require.js:1143:22)
at Object.Module.init (http://192.168.33.10:8080/lib/js/require.js:774:26)
at callGetModule (http://192.168.33.10:8080/lib/js/require.js:1170:63)
at Object.context.completeLoad (http://192.168.33.10:8080/lib/js/require.js:1564:25)
at HTMLScriptElement.context.onScriptLoad (http://192.168.33.10:8080/lib/js/require.js:1671:29)
```

If I downgrade to RCloud 1.3.4, make a new notebook, and upgrade, then I don't get this error. So it appears to be a "fresh install" problem.

**Comment by dougmet** [comment]
It's not ideal that fresh_start is called as root here but I've had the same error when I ran as a normal user as well.

**Comment by gordonwoodhull** [comment]
This is an issue with rgithub:

https://github.com/cscheid/rgithub/issues/50

Install @s-u's fork of rgithub instead:

https://github.com/s-u/rgithub/

**Comment by s-u** [comment]
I have temporarily changed RForge.net to build off my fork (until fixed on cscheid), so using the RForge.net repo should work now.

**Comment by dougmet** [comment]
OK great, thanks for that. I'll update the provisioning and report back.

**Comment by dougmet** [comment]
That seems to have done it for me. Also, from a quick check it seems to be considerably more stable than previous installs I've had that would regularly hang when updating the notebook.
