### ISSUE TITLE
bogus "You may need to login" message

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1614]
This after the notebook has successfully run:
![image](https://cloud.githubusercontent.com/assets/1366709/9212308/e8289c44-4055-11e5-8bff-fcde021dd5b2.png)

Console log:
```
TypeError: Cannot read property '__active' of undefined
    at Object.ui_utils.editable (http://127.0.0.1:8080/js/rcloud_bundle.js:1212:66)
    at Object.RCloud.UI.notebook_title.result.set (http://127.0.0.1:8080/js/rcloud_bundle.js:6946:22)
    at on_load (http://127.0.0.1:8080/shell_tab.js:20:34)
From previous event:
    at http://127.0.0.1:8080/shell_tab.js:53:20
From previous event:
    at Object.RCloud.UI.with_progress (http://127.0.0.1:8080/js/rcloud_bundle.js:7282:10)
    at do_load (http://127.0.0.1:8080/shell_tab.js:41:26)
    at Object.result.load_notebook (http://127.0.0.1:8080/shell_tab.js:116:20)
    at http://127.0.0.1:8080/view.js:56:26
From previous event:
    at http://127.0.0.1:8080/view.js:55:27
```

I have no idea why this is only showing up now, looks like it's trying to make the notebook title editable when it's not.

**Comment by anatoliyg** [comment]
You were right, it had to do with me removing the navbar from view.html. once the navbar was put back in place, the error disappears, so closing.
