### ISSUE TITLE
UI should be tolerant of garbage in the notebook registry

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2378]
Currently editor_tab throws errors in about eight places when reading or writing the registry. This is extremely brittle and can cause the UI to become unusable.

In particular, I'm running into this one. But I think all exceptions in the editor tab should be reviewed and probably replaced with `console.warn`.

```
Error: incomplete notebook entry (has it been shown yet?)
    at as_folder_hierarchy (https://rcloud.web.att.com/editor_tab.js:235:18)
    at https://rcloud.web.att.com/editor_tab.js:181:29
From previous event:
    at load_user_notebooks (https://rcloud.web.att.com/editor_tab.js:175:48)
    at update_notebook_model (https://rcloud.web.att.com/editor_tab.js:113:16)
    at update_notebook_from_gist (https://rcloud.web.att.com/editor_tab.js:1022:16)
    at https://rcloud.web.att.com/editor_tab.js:1801:48
From previous event:
    at https://rcloud.web.att.com/editor_tab.js:1800:41
From previous event:
    at result.load_callback (https://rcloud.web.att.com/editor_tab.js:1783:39)
From previous event:
    at https://rcloud.web.att.com/editor_tab.js:1363:22
From previous event:
```

**Comment by gordonwoodhull** [comment]
Must print IDs to the console every time there is an error.

Also it would probably make sense to use higher-level APIs instead of twiddling individual keys from the front-end. Although this is not always possible, because e.g. the front end does need to manipulate stars and recents individually.

**Comment by gordonwoodhull** [comment]
Most of the `throw`s seem to detect bad logic, so they are appropriate. I am not sure that this is the only one, but I'll only hit the "incomplete notebook entry" error for now.
