### ISSUE TITLE
(R)Markdown autocompletion doesn't work

### ISSUE THREAD

**Issue by useless5771** [att/rcloud#2429]
When you try to run autocomplete in Markdown or RMarkdown cells the following error is logged in the console:
`

Uncaught TypeError: Cannot read property '$keywordList' of undefined
    at Mode.$createKeywordList (http://127.0.0.1:8080/lib/ace_bundle.js:6377:56)
    at Mode.getCompletions (http://127.0.0.1:8080/lib/ace_bundle.js:6381:50)
    at Object.getCompletions (http://127.0.0.1:8080/lib/ace_bundle.js:26521:41)
    at http://127.0.0.1:8080/lib/ace_bundle.js:26215:23
    at Array.forEach (native)
    at Autocomplete.gatherCompletions (http://127.0.0.1:8080/lib/ace_bundle.js:26214:27)
    at Autocomplete.updateCompletions (http://127.0.0.1:8080/lib/ace_bundle.js:26268:14)
    at Autocomplete.showPopup (http://127.0.0.1:8080/lib/ace_bundle.js:26248:14)
    at Object.exec (http://127.0.0.1:8080/lib/ace_bundle.js:26380:26)
    at http://127.0.0.1:8080/lib/ace_bundle.js:10881:26
    at CommandManager.EventEmitter._emit.EventEmitter._dispatchEvent (http://127.0.0.1:8080/lib/ace_bundle.js:3396:16)
    at CommandManager.exec (http://127.0.0.1:8080/lib/ace_bundle.js:10909:30)
    at KeyBinding.$callKeyboardHandlers (http://127.0.0.1:8080/lib/ace_bundle.js:4097:36)
    at KeyBinding.onCommandKey (http://127.0.0.1:8080/lib/ace_bundle.js:4121:14)
    at Editor.onCommandKey (http://127.0.0.1:8080/lib/ace_bundle.js:12433:25)
    at normalizeCommandKeys (http://127.0.0.1:8080/lib/ace_bundle.js:1656:12)
$createKeywordList @ ace.js:6369
getCompletions @ ace.js:6373
getCompletions @ ext-language_tools.js:1808
(anonymous) @ ext-language_tools.js:1502
gatherCompletions @ ext-language_tools.js:1501
updateCompletions @ ext-language_tools.js:1555
showPopup @ ext-language_tools.js:1535
exec @ ext-language_tools.js:1667
(anonymous) @ ace.js:10873
EventEmitter._emit.EventEmitter._dispatchEvent @ ace.js:3388
exec @ ace.js:10901
$callKeyboardHandlers @ ace.js:4089
onCommandKey @ ace.js:4113
onCommandKey @ ace.js:12425
normalizeCommandKeys @ ace.js:1648
(anonymous) @ ace.js:1667

`

Looked briefly at this and it looks like rmarkdown.js does not set $highlightRules attribute just $tokenizer.

**Comment by useless5771** [comment]
Error is not thrown any more and auto-completion works for RMarkdown and Markdown cells.

Fixed by https://github.com/att/rcloud/pull/2430

**Comment by gordonwoodhull** [comment]
Fixed by #2515
