### ISSUE TITLE
Python autocompletion seems broken in 1.9

### ISSUE THREAD

**Issue by s-u** [att/rcloud#2521]
Trying to use completion in Python cell causes

TypeError: session.$mode.getCompletionsAsync is not a function
at Object.getCompletions (https://rcloud.research.att.com/lib/ace_bundle.js:26617:23)
at Autocomplete.gatherCompletions (https://rcloud.research.att.com/lib/ace_bundle.js:26258:19)
at Autocomplete.<anonymous> (https://rcloud.research.att.com/lib/ace_bundle.js:26313:18)
at Autocomplete.<anonymous> (https://rcloud.research.att.com/lib/ace_bundle.js:26326:21)
at Autocomplete.<anonymous> (https://rcloud.research.att.com/lib/ace_bundle.js:26347:24)
at Autocomplete.<anonymous> (https://rcloud.research.att.com/lib/ace_bundle.js:26265:18)
at Object.getCompletions (https://rcloud.research.att.com/lib/ace_bundle.js:26602:11)
From previous event:
at PythonCompletions.getCompletions (https://rcloud.research.att.com/lib/ace_bundle.js:28205:34)
at Object.getCompletions (https://rcloud.research.att.com/lib/ace_bundle.js:26584:38)
at Autocomplete.gatherCompletions (https://rcloud.research.att.com/lib/ace_bundle.js:26258:19)
at Autocomplete.<anonymous> (https://rcloud.research.att.com/lib/ace_bundle.js:26313:18)
at Autocomplete.updateCompletions (https://rcloud.research.att.com/lib/ace_bundle.js:26319:9)
at Autocomplete.showPopup (https://rcloud.research.att.com/lib/ace_bundle.js:26290:14)
at Object.exec (https://rcloud.research.att.com/lib/ace_bundle.js:26437:26)
at Object.exec (https://rcloud.research.att.com/js/rcloud_bundle.js:940:47)
at https://rcloud.research.att.com/lib/ace_bundle.js:10881:26
at CommandManager.EventEmitter._emit.EventEmitter._dispatchEvent (https://rcloud.research.att.com/lib/ace_bundle.js:3396:16)
at CommandManager.exec (https://rcloud.research.att.com/lib/ace_bundle.js:10909:30)
at CommandManager.exec (https://rcloud.research.att.com/lib/ace_bundle.js:10894:26)
at KeyBinding.$callKeyboardHandlers (https://rcloud.research.att.com/lib/ace_bundle.js:4097:36)
at KeyBinding.onCommandKey (https://rcloud.research.att.com/lib/ace_bundle.js:4121:14)
at Editor.onCommandKey (https://rcloud.research.att.com/lib/ace_bundle.js:12433:25)
at normalizeCommandKeys (https://rcloud.research.att.com/lib/ace_bundle.js:1656:12)
at HTMLTextAreaElement.<anonymous> (https://rcloud.research.att.com/lib/ace_bundle.js:1675:26)

and hitting auto-complete twice (`<tab><tab>`) opens a new tab

**Comment by gordonwoodhull** [comment]
The difficulty here is getting Python support working for @useless5771. I don't think anyone on the Mango side has had any success with it.

Personally, I have tried it a few times on a few machines, and it worked once. I have no idea how to troubleshoot it.

**Comment by s-u** [comment]
Well, but the above doesn't even need any Python support (Python is not even existent at that point) - it fails in the UI not in Python.

**Comment by gordonwoodhull** [comment]
Yes, you would think so, but for some reason, if rcloud.python is in the broken state, you get the following error instead. The "bad file descriptor" is the same error you get for executing python.

I'm not going to look into this any further right now, since the fix for this issue is easy: I just copy the mode-r code from 6c90a55949121. I also don't understand why the fix for markdown mode (which was a silent failure) works for this hard python error.

```
Error: get_completions: Error in py.eval(paste("runner = notebook_runner.NotebookRunner(rcloud_python_lib_path='", :
Python exception: <type 'exceptions.OSError'> [Errno 9] Bad file descriptor
R trace:
.Call(rpy_eval, code, globals, locals, !quiet)
py.eval(paste("runner = notebook_runner.NotebookRunner(rcloud_python_lib_path='",
path, "', extra_arguments=['--matplotlib=inline'], executable='python')",
sep = ""))
.start.python(thissession)
.session$languages[[language]]$complete(text, pos, .session)
fun(...)
at success (http://minimonolith.dev.local:8080/js/rcloud_bundle.js:32:23)
From previous event:
at Object.get_completionsAsync (http://minimonolith.dev.local:8080/js/rcloud_bundle.js:38:54)
at Object.rcloud.get_completions (http://minimonolith.dev.local:8080/js/rcloud_bundle.js:494:33)
at PythonCompletions.getCompletions (http://minimonolith.dev.local:8080/lib/ace_bundle.js:28199:18)
at Object.getCompletions (http://minimonolith.dev.local:8080/lib/ace_bundle.js:26584:38)
at Autocomplete.gatherCompletions (http://minimonolith.dev.local:8080/lib/ace_bundle.js:26258:19)
at Autocomplete.<anonymous> (http://minimonolith.dev.local:8080/lib/ace_bundle.js:26313:18)
at Autocomplete.updateCompletions (http://minimonolith.dev.local:8080/lib/ace_bundle.js:26319:9)
at Autocomplete.showPopup (http://minimonolith.dev.local:8080/lib/ace_bundle.js:26290:14)
at Object.exec (http://minimonolith.dev.local:8080/lib/ace_bundle.js:26437:26)
at Object.exec (http://minimonolith.dev.local:8080/js/rcloud_bundle.js:940:47)
at http://minimonolith.dev.local:8080/lib/ace_bundle.js:10881:26
at CommandManager.EventEmitter._emit.EventEmitter._dispatchEvent (http://minimonolith.dev.local:8080/lib/ace_bundle.js:3396:16)
at CommandManager.exec (http://minimonolith.dev.local:8080/lib/ace_bundle.js:10909:30)
at CommandManager.exec (http://minimonolith.dev.local:8080/lib/ace_bundle.js:10894:26)
at KeyBinding.$callKeyboardHandlers (http://minimonolith.dev.local:8080/lib/ace_bundle.js:4097:36)
at KeyBinding.onCommandKey (http://minimonolith.dev.local:8080/lib/ace_bundle.js:4121:14)
at Editor.onCommandKey (http://minimonolith.dev.local:8080/lib/ace_bundle.js:12433:25)
at normalizeCommandKeys (http://minimonolith.dev.local:8080/lib/ace_bundle.js:1656:12)
at HTMLTextAreaElement.<anonymous> (http://minimonolith.dev.local:8080/lib/ace_bundle.js:1675:26)
```
