### ISSUE TITLE
Autocomplete in Python gives error in session pane

### ISSUE THREAD

**Issue by ejen1** [att/rcloud#2584]
I started typing "impo" and pressed auto-complete

**python2:**

[IPKernelApp] ERROR | Failed to create history session in /home/eugene/.ipython/profile_default/history.sqlite. History will not be saved.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/IPython/core/history.py", line 549, in __init__
    self.new_session()
  File "", line 2, in new_session
  File "/usr/lib/python2.7/dist-packages/IPython/core/history.py", line 60, in needs_sqlite
    return f(self, *a, **kw)
  File "/usr/lib/python2.7/dist-packages/IPython/core/history.py", line 575, in new_session
    NULL, "") """, (datetime.datetime.now(),))
OperationalError: unable to open database file

**python3:**

[IPKernelApp] ERROR | Failed to create history session in /home/eugene/.ipython/profile_default/history.sqlite. History will not be saved.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/history.py", line 543, in __init__
    self.new_session()
  File "", line 2, in new_session
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/history.py", line 58, in needs_sqlite
    return f(self, *a, **kw)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/history.py", line 569, in new_session
    NULL, "") """, (datetime.datetime.now(),))
sqlite3.OperationalError: unable to open database file

**Comment by gordonwoodhull** [comment]
Thanks @ejen1! Strangely, I can't reproduce this. Could you check if you have a folder `.ipython` in your home directory, and if so, what permissions are on `~/.ipython/profile_default`?

When I tested, this directory and database was created the first time I invoked autocomplete.

**Comment by ejen1** [comment]
that issue was related to me running out of disk space.
Closing the issue

**Comment by ejen1** [comment]
that issue was related to me running out of disk space.
Closing the issue
