### ISSUE TITLE
notebook sometimes disappears from tree when version is tagged

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2696]
click a hash to give a custom tag to a version of a notebook (named 'mini.html')

when enter is pressed, the notebook disappears (but otherwise everything seems to work)

seems like this only happens if
1. this was the first notebook loaded (ie was current notebook at startup)
2. there also was a current version or tag in the url

but once or twice i think i saw it happen with a later notebook

**Comment by gordonwoodhull** [comment]
Additionally, when  navigating away from the notebook and then returning to it using Recent Notebooks, the following error is thrown:

```
TypeError: Cannot read property 'id' of undefined
    at JqTreeWidget.updateNode (http://127.0.0.1:8080/lib/js/tree.jquery.js:1336:51)
    at callFunction (http://127.0.0.1:8080/lib/js/tree.jquery.js:100:40)
    at jQuery.fn.init.$.fn.<computed> [as tree] (http://127.0.0.1:8080/lib/js/tree.jquery.js:118:20)
    at Array.<anonymous> (http://127.0.0.1:8080/js/rcloud_bundle.js:15994:29)
    at event.notify (http://127.0.0.1:8080/js/rcloud_bundle.js:5590:39)
    at notebook_tree_model.update_tree_node (http://127.0.0.1:8080/js/rcloud_bundle.js:14533:33)
    at notebook_tree_model.update_tree (http://127.0.0.1:8080/js/rcloud_bundle.js:15122:26)
    at notebook_tree_model.update_tree_entry (http://127.0.0.1:8080/js/rcloud_bundle.js:15223:29)
    at notebook_tree_model.update_notebook_view (http://127.0.0.1:8080/js/rcloud_bundle.js:14630:26)
    at http://127.0.0.1:8080/js/rcloud_bundle.js:14520:33
From previous event:
    at notebook_tree_model.update_notebook_from_gist (http://127.0.0.1:8080/js/rcloud_bundle.js:14519:18)
    at notebook_tree_controller.update_notebook_from_gist (http://127.0.0.1:8080/js/rcloud_bundle.js:16415:32)
    at http://127.0.0.1:8080/editor_tab.js:786:65
From previous event:
    at http://127.0.0.1:8080/editor_tab.js:785:41
From previous event:
    at http://127.0.0.1:8080/editor_tab.js:768:39
From previous event:
    at http://127.0.0.1:8080/editor_tab.js:161:22
From previous event:
    at Object.load_notebook (http://127.0.0.1:8080/editor_tab.js:159:27)
    at Object.open_notebook (http://127.0.0.1:8080/editor_tab.js:187:22)
    at HTMLAnchorElement.click_recent (http://127.0.0.1:8080/editor_tab.js:579:26)
    at HTMLAnchorElement.dispatch (http://127.0.0.1:8080/lib/js/jquery-2.1.1.js:4409:9)
    at HTMLAnchorElement.elemData.handle (http://127.0.0.1:8080/lib/js/jquery-2.1.1.js:4095:28)
```
