### ISSUE TITLE
file.choose() is not supported

### ISSUE THREAD

**Issue by GanapatiBhat** [att/rcloud#968]
I am getting the error something like below

Possibly unhandled Error: send: Error in file.choose() : sorry, direct console input is not supported 
    at success (http://127.0.0.1:8080/js/rcloud_bundle.js:118:23)
    at tryCatch1 (http://127.0.0.1:8080/lib/js/bluebird.js:4988:19)
    at Promise$_callHandler [as _callHandler] (http://127.0.0.1:8080/lib/js/bluebird.js:2333:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (http://127.0.0.1:8080/lib/js/bluebird.js:2349:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (http://127.0.0.1:8080/lib/js/bluebird.js:2521:14)
    at Promise$_fulfillPromises [as _fulfillPromises] (http://127.0.0.1:8080/lib/js/bluebird.js:2666:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (http://127.0.0.1:8080/lib/js/bluebird.js:157:12)
    at Async$consumeFunctionBuffer (http://127.0.0.1:8080/lib/js/bluebird.js:120:14)
    at MutationObserver.Promise$_Scheduler (http://127.0.0.1:8080/lib/js/bluebird.js:4260:17) bluebird.js:458

**Comment by gordonwoodhull** [comment]
fixed in 1.3 - still needs #1191 input prompt text but the basic functionality works
